image: node:latest

before_script:
  - npm install

stages:
  - test
  - build

test:
  stage: test
  script: npm run test
  
dist_win:
  stage: build
  image: electronuserland/builder:wine
  script: npm run dist:win
  artifacts:
    paths:
      - dist/out/*.exe
      - dist/out/*.blockmap
  
dist_linux:
  stage: build
  image: electronuserland/builder:10
  script: npm run dist:linux
  artifacts:
    paths:
      - dist/out/*.snap
      - dist/out/*.AppImage
      - dist/out/*.deb
