image: node:latest

before_script:
  - npm install

stages:
  - test
  - build

test:
  stage: test
  script: npm run test
  
dist_win:
  stage: build
  script: npm run dist:win
  artifacts:
    paths:
      - dist/out
  
dist_linux:
  stage: build
  script: npm run dist:linux
  artifacts:
    paths:
      - dist/out
